[build]
  command = "npm run build"
  publish = "dist/frontend"

[[redirects]]
  from = "/api/*"
  to = "https://35.193.57.27/api/:splat"
  status = 200
  force = true
  
  # Headers para permitir requisições cross-origin
  # Headers para permitir requisições cross-origin
  [redirects.headers]
    X-Forwarded-Proto = "https"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
